spring:
  application:
    name: whkstatusApi
  datasource:
    url: jdbc:mysql://localhost:3306/webhook-poc
    username: root
    password: root
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

  graphql:
    graphiql:
      enabled:
        true
